create table if not exists public.telegram_posts (
    id bigint generated by default as identity primary key,
    produto_id bigint not null,
    grupo_id bigint not null,
    message_id bigint,
    status text not null default 'enviado',
    enviado_em timestamptz not null default now(),
    constraint telegram_posts_produto_grupo_unique unique (produto_id, grupo_id)
);

create index if not exists telegram_posts_produto_id_idx
    on public.telegram_posts (produto_id);
